### ISSUE TITLE
cusparseScsrmm2 is deprecated in CUDA 11

### ISSUE THREAD

**Issue by PengchengWang** [hgyhungry/ge-spmm#8]
After running `source compile.sh` the fllowing error occured:
```bash
spmm_test.cu(660): error: identifier "cusparseScsrmm2" is undefined
```
But in the paper **Efficient Sparse Matrix Kernels based on Adaptive Workload-Balancing and Parallel-Reduction** the result is compared with cuda11.
Please update the code to fit cuda11.

Thankyou~

**Comment by hgyhungry** [comment]
Hi @PengchengWang , 
The evaluation artifact of this arxiv paper will be released at the dgSPARSE project, instead of this repo. In that project, we support comparison against cusparse v11+. 
You can check update of kernels in dgSPARSE-library (https://github.com/dgSPARSE/dgSPARSE-Library), and check how to evaluate it against cusparse without changing source code, by referring to dgSPARSE-wrapper (https://github.com/dgSPARSE/dgSPARSE-Wrapper). 
The kernel source code will be released in the next update, within this month. 
I will update the arxiv preprint to link readers to the correct repo. Thank you for this message.

**Comment by hgyhungry** [comment]
Temporally, you can access the source code from my fork https://github.com/hgyhungry/dgSPARSE-Library
Follow the example/README.md for running. It uses cusparse v11 as baseline.
The change will be merged to dgsparse project in next update.

**Comment by hgyhungry** [comment]
closing this
